### PR TITLE
Remove illuminate/support and laravel/helpers

### PR DESCRIPTION
**Pull request by vinkla**
This pull request removes the `illuminate/support` and `laravel/helpers` packages. Laravel recently moved their array and string helper functions from Laravel framework into [its own package](https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers) making their helper functions optional.

The `illuminate/support` and `laravel/helpers` packages currently installs a lot of packages. This is the output from when I removed the dependencies:

```sh
- Removing symfony/translation (v4.2.8)
- Removing symfony/contracts (v1.1.0)
- Removing psr/simple-cache (1.0.1)
- Removing psr/container (1.0.0)
- Removing nesbot/carbon (2.17.1)
- Removing laravel/helpers (v1.0.1)
- Removing illuminate/support (v5.8.15)
- Removing illuminate/contracts (v5.8.15)
- Removing doctrine/inflector (v1.3.0)
```

It is [recommended to not have `illuminate/support` package](https://mattallan.me/posts/dont-use-illuminate-support/) listed a dependency since it is made for Laravel. It comes with a lot of classes which we don't use in WordPlate:

```sh
├── AggregateServiceProvider.php
├── Arr.php
├── Carbon.php
├── Collection.php
├── Composer.php
├── DateFactory.php
├── Facades
│   ├── App.php
│   ├── Artisan.php
│   ├── Auth.php
│   ├── Blade.php
│   ├── Broadcast.php
│   ├── Bus.php
│   ├── Cache.php
│   ├── Config.php
│   ├── Cookie.php
│   ├── Crypt.php
│   ├── DB.php
│   ├── Date.php
│   ├── Event.php
│   ├── Facade.php
│   ├── File.php
│   ├── Gate.php
│   ├── Hash.php
│   ├── Input.php
│   ├── Lang.php
│   ├── Log.php
│   ├── Mail.php
│   ├── Notification.php
│   ├── Password.php
│   ├── Queue.php
│   ├── Redirect.php
│   ├── Redis.php
│   ├── Request.php
│   ├── Response.php
│   ├── Route.php
│   ├── Schema.php
│   ├── Session.php
│   ├── Storage.php
│   ├── URL.php
│   ├── Validator.php
│   └── View.php
├── Fluent.php
├── HigherOrderCollectionProxy.php
├── HigherOrderTapProxy.php
├── HtmlString.php
├── InteractsWithTime.php
├── LICENSE.md
├── Manager.php
├── MessageBag.php
├── NamespacedItemResolver.php
├── Optional.php
├── Pluralizer.php
├── ProcessUtils.php
├── ServiceProvider.php
├── Str.php
├── Testing
│   └── Fakes
│       ├── BusFake.php
│       ├── EventFake.php
│       ├── MailFake.php
│       ├── NotificationFake.php
│       ├── PendingMailFake.php
│       └── QueueFake.php
├── Traits
│   ├── CapsuleManagerTrait.php
│   ├── ForwardsCalls.php
│   ├── Localizable.php
│   └── Macroable.php
├── ViewErrorBag.php
├── composer.json
└── helpers.php
```

...it also installs the `illuminate/contracts` package:

```
├── Auth
│   ├── Access
│   │   ├── Authorizable.php
│   │   └── Gate.php
│   ├── Authenticatable.php
│   ├── CanResetPassword.php
│   ├── Factory.php
│   ├── Guard.php
│   ├── MustVerifyEmail.php
│   ├── PasswordBroker.php
│   ├── PasswordBrokerFactory.php
│   ├── StatefulGuard.php
│   ├── SupportsBasicAuth.php
│   └── UserProvider.php
├── Broadcasting
│   ├── Broadcaster.php
│   ├── Factory.php
│   ├── ShouldBroadcast.php
│   └── ShouldBroadcastNow.php
├── Bus
│   ├── Dispatcher.php
│   └── QueueingDispatcher.php
├── Cache
│   ├── Factory.php
│   ├── Lock.php
│   ├── LockProvider.php
│   ├── LockTimeoutException.php
│   ├── Repository.php
│   └── Store.php
├── Config
│   └── Repository.php
├── Console
│   ├── Application.php
│   └── Kernel.php
├── Container
│   ├── BindingResolutionException.php
│   ├── Container.php
│   └── ContextualBindingBuilder.php
├── Cookie
│   ├── Factory.php
│   └── QueueingFactory.php
├── Database
│   └── ModelIdentifier.php
├── Debug
│   └── ExceptionHandler.php
├── Encryption
│   ├── DecryptException.php
│   ├── EncryptException.php
│   └── Encrypter.php
├── Events
│   └── Dispatcher.php
├── Filesystem
│   ├── Cloud.php
│   ├── Factory.php
│   ├── FileExistsException.php
│   ├── FileNotFoundException.php
│   └── Filesystem.php
├── Foundation
│   └── Application.php
├── Hashing
│   └── Hasher.php
├── Http
│   └── Kernel.php
├── LICENSE.md
├── Mail
│   ├── MailQueue.php
│   ├── Mailable.php
│   └── Mailer.php
├── Notifications
│   ├── Dispatcher.php
│   └── Factory.php
├── Pagination
│   ├── LengthAwarePaginator.php
│   └── Paginator.php
├── Pipeline
│   ├── Hub.php
│   └── Pipeline.php
├── Queue
│   ├── EntityNotFoundException.php
│   ├── EntityResolver.php
│   ├── Factory.php
│   ├── Job.php
│   ├── Monitor.php
│   ├── Queue.php
│   ├── QueueableCollection.php
│   ├── QueueableEntity.php
│   └── ShouldQueue.php
├── Redis
│   ├── Connection.php
│   ├── Factory.php
│   └── LimiterTimeoutException.php
├── Routing
│   ├── BindingRegistrar.php
│   ├── Registrar.php
│   ├── ResponseFactory.php
│   ├── UrlGenerator.php
│   └── UrlRoutable.php
├── Session
│   └── Session.php
├── Support
│   ├── Arrayable.php
│   ├── DeferrableProvider.php
│   ├── Htmlable.php
│   ├── Jsonable.php
│   ├── MessageBag.php
│   ├── MessageProvider.php
│   ├── Renderable.php
│   └── Responsable.php
├── Translation
│   ├── HasLocalePreference.php
│   ├── Loader.php
│   └── Translator.php
├── Validation
│   ├── Factory.php
│   ├── ImplicitRule.php
│   ├── Rule.php
│   ├── ValidatesWhenResolved.php
│   └── Validator.php
├── View
│   ├── Engine.php
│   ├── Factory.php
│   └── View.php
└── composer.json
```

Below I've listed benefits and drawbacks. Please comment if you have any suggestions.

**Benefits:**

- Helper functions will become optional
- Fewer packages to download and install
- Less dependencies to maintain in `wordplate/framework`
- We save about 3 MB during installation: 5.5 MB -> 2.5 MB
- Makes it easier to use theme's outside WordPlate

**Drawbacks:**

- We need to maintain our own `env()` function

cc @wordplate/developers

### CODE REVIEW

**Comment by fiskhandlarn** [comment]
"This branch has conflicts that must be resolved", does this needs to be fixed before merging?

**Comment by vinkla** [comment]
You're right. I've pushed an update to fix the conflicts!

**Review by puredazzle — APPROVED** [review]
Sounds good.

**Review by fiskhandlarn — APPROVED** [review]

**Comment by vinkla** [comment]
happy

**Pull request merged**
