### PR TITLE
Set blog descripion from config file

### PR DESCRIPTION
**Pull request by puredazzle**
Added the option to set the blog description via the config files. Instead of the standard:

> Just another WordPress site

### CODE REVIEW

**Comment by vinkla** [comment]
Is this the same as you set under settings in WordPress admin?

**Comment by puredazzle** [comment]
@vinkla yes, I always forget to remove that, so it would be nice to reset/edit it from our framework.

**Comment by vinkla** [comment]
Sound cool! Lets wait for the tests to finish.

**Comment by puredazzle** [comment]
@vinkla this is done now. can't squash thou....

**Comment by vinkla** [comment]
I've squashed them. Merging…

**Comment by vinkla** [comment]
…done. Thanks!

**Pull request merged**
